#!/bin/bash
source ./source/data_base
path=$PWD



fl0=output
fl1=phi${phi}N${N}gam${gam}T${T}K${K}Dr${Dr}v${v0}
fl2=L${L}h${h}

fl=./${fl0}/${fl1}/${fl2}

echo $fl 
mkdir -p ${fl}/obs/zeta

cd ${fl}/obs/f



for U in ${U_base} 
do

    file=F_K${K}_T${T}_gam${gam}_phi${phi}_N${N}_L${L}_h${h}_Dr${Dr}_v${v0}_U${U}_length${running_length}_ens

cp ${file}_p* ../zeta

cp F_K${K}_T${T}_gam${gam}_phi${phi}_N${N}_L${L}_h${h}_Dr${Dr}_v${v0}_U${U}_ens_avg ../zeta
done #U




cd ../zeta
rm zeta


#echo "$PWD"




for U in ${U_base}
do


    #file=F_K${K}_T${T}_gam${gam}_phi${phi}_N${N}_L${L}_h${h}_Dr${Dr}_v${v0}_U${U}_length${running_length}_ens_p*
    file=F_K${K}_T${T}_gam${gam}_phi${phi}_N${N}_L${L}_h${h}_Dr${Dr}_v${v0}_U${U}_ens_avg
    awk -v U=${U} -v gam=${gam} ' 
                BEGIN{Fx=0;Fy=0;Fxx=0;Fyy=0;sum=0;} 
                { if (FNR>=6) {Fx+=(-$2/U);Fy+=(-$3/U);Fxx+=$2*$2/(U*U); Fyy+=$3*$3/(U*U); sum++;} } 
                END { aFx=Fx/sum; aFy=Fy/sum; 
                      aFxx=Fxx/sum;aFyy=Fyy/sum; 
                      sd_Fx=sqrt( (aFxx-aFx*aFx)*(sum/(sum-1))); 
                      sd_Fy=sqrt( (aFyy-aFy*aFy)*(sum/(sum-1)));      
                      print U, aFx/gam, sd_Fx/gam, aFy/gam, sd_Fy/gam 
                    }' ${file} >> zeta




done #U


mkdir -p ${path}/plot



cp zeta ${path}/plot/K${K}_T${T}_gam${gam}_N${N}_L${L}_h${h}_Dr${Dr}_v${v0}_length${running_length}_zeta_p${nd}

cd ${path}/plot


#vi K${K}_T${T}_gam${gam}_phi${phi}_L${L}_h${h}_Dr${Dr}_v${v0}_zeta
echo "${path}/plot"
#-------------------------------------------------
gnuplot  -persist  << EOF

####set logs xy
set logs x
plot  "K${K}_T${T}_gam${gam}_N${N}_L${L}_h${h}_Dr${Dr}_v${v0}_length${running_length}_zeta_p${nd}"  using 1:2  w l lw 3, '' us 1:2:3 w err lw 5

EOF
# -------------------------------------------
