#!/bin/bash
#g++ -O3 -std=c++11 test_ic.cc ic.cc field.cc 



source /public/software/profile.d/mpi_openmpi-2.0.0-gcc-5.4.0.sh
mpic++  -O3 -std=c++11 ABPs.cc ic.cc dyn.cc box.cc interaction.cc field.cc obs.cc
#g++ -O3 -std=c++11 ABPs.cc ic.cc dyn.cc box.cc interaction.cc field.cc obs.cc
#g++ -O3 -std=c++11 test_ic.cc ic.cc dyn_old.cc interaction.cc box.cc field.cc obs.cc Memory.cc gaussian.cc


        echo "
              #!/bin/sh -f
              #PBS -N U${U_base}nd${nd}
              #PBS -l nodes=1:ppn=1
              #PBS -o test.stdout
              #PBS -e test.stderr
              #PBS -q low
              ###PBS -q high
              ###PBS -q middle
	      source /public/software/profile.d/mpi_openmpi-2.0.0-gcc-5.4.0.sh
	      ###echo ============ after source ===============
	      ###ldd a.out
              ###nprocs='wc -l < $PBS_NODEFILE'

              cd $PWD

              ###echo \"${U} ${nd}\"|./a.out
              
              ###echo $PWD

              mpirun ./a.out
              "> mpi 
    qsub mpi   # submit the job






